version: "3"
    
services:
  back:
    build: ./back
    restart: always
    volumes:
        - ./data:/app/data
    ports:
      - "1337:1337"
    
  front:
    depends_on:
      - back
    build: ./front
    ports:
      - "8070:8080"
    restart: always